// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (room_id, game_id, room_player_id, message)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, game_id, room_player_id, message, created_at
`

type CreateChatMessageParams struct {
	RoomID       pgtype.UUID `json:"room_id"`
	GameID       pgtype.UUID `json:"game_id"`
	RoomPlayerID pgtype.UUID `json:"room_player_id"`
	Message      string      `json:"message"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.RoomID,
		arg.GameID,
		arg.RoomPlayerID,
		arg.Message,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameID,
		&i.RoomPlayerID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
