// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckDisplayNameExists(ctx context.Context, arg CheckDisplayNameExistsParams) (bool, error)
	CheckRoomCodeExists(ctx context.Context, code string) (bool, error)
	CheckUserEmailExists(ctx context.Context, email string) (bool, error)
	CountRoomPlayersById(ctx context.Context, id pgtype.UUID) (int64, error)
	CountRoomPlayersByRoomId(ctx context.Context, roomID pgtype.UUID) (int64, error)
	CountRoomsById(ctx context.Context, id pgtype.UUID) (int64, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateGameEvent(ctx context.Context, arg CreateGameEventParams) (GameEvent, error)
	CreateGamePlayer(ctx context.Context, arg CreateGamePlayerParams) (GamePlayer, error)
	CreateGameStateSnapshot(ctx context.Context, arg CreateGameStateSnapshotParams) (GameStateSnapshot, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (CreateRoomRow, error)
	CreateRoomPlayer(ctx context.Context, arg CreateRoomPlayerParams) (CreateRoomPlayerRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetGameById(ctx context.Context, id pgtype.UUID) (Game, error)
	GetGameEventsByGameId(ctx context.Context, gameID pgtype.UUID) ([]GameEvent, error)
	GetGameEventsByGameIdAfter(ctx context.Context, arg GetGameEventsByGameIdAfterParams) ([]GameEvent, error)
	GetGamesByRoomId(ctx context.Context, roomID pgtype.UUID) ([]Game, error)
	GetLatestGameStateSnapshotByGameId(ctx context.Context, gameID pgtype.UUID) (GameStateSnapshot, error)
	GetRoomByCode(ctx context.Context, code string) (GetRoomByCodeRow, error)
	GetRoomById(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoomCodeById(ctx context.Context, id pgtype.UUID) (string, error)
	GetRoomPasswordHashById(ctx context.Context, id pgtype.UUID) (pgtype.Text, error)
	GetRoomPlayersByGameId(ctx context.Context, gameID pgtype.UUID) ([]GetRoomPlayersByGameIdRow, error)
	GetRoomPlayersByRoomId(ctx context.Context, roomID pgtype.UUID) ([]GetRoomPlayersByRoomIdRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) error
}

var _ Querier = (*Queries)(nil)
