// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDisplayNameExists = `-- name: CheckDisplayNameExists :one
SELECT EXISTS(SELECT 1 FROM room_players WHERE room_id = $1 AND display_name = $2) as exists
`

type CheckDisplayNameExistsParams struct {
	RoomID      pgtype.UUID `json:"room_id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CheckDisplayNameExists(ctx context.Context, arg CheckDisplayNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkDisplayNameExists, arg.RoomID, arg.DisplayName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkRoomCodeExists = `-- name: CheckRoomCodeExists :one
SELECT EXISTS(SELECT 1 FROM rooms WHERE code = $1) as exists
`

func (q *Queries) CheckRoomCodeExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, checkRoomCodeExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countRoomPlayersById = `-- name: CountRoomPlayersById :one
SELECT COUNT(*) FROM room_players WHERE id = $1
`

func (q *Queries) CountRoomPlayersById(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomPlayersById, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoomPlayersByRoomId = `-- name: CountRoomPlayersByRoomId :one
SELECT COUNT(*) FROM room_players WHERE room_id = $1
`

func (q *Queries) CountRoomPlayersByRoomId(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomPlayersByRoomId, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoomsById = `-- name: CountRoomsById :one
SELECT COUNT(*) FROM rooms WHERE id = $1
`

func (q *Queries) CountRoomsById(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomsById, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (code, password_hash, settings_json)
VALUES ($1, $2, $3)
RETURNING id, code, created_at, updated_at
`

type CreateRoomParams struct {
	Code         string      `json:"code"`
	PasswordHash pgtype.Text `json:"password_hash"`
	SettingsJson []byte      `json:"settings_json"`
}

type CreateRoomRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (CreateRoomRow, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Code, arg.PasswordHash, arg.SettingsJson)
	var i CreateRoomRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoomPlayer = `-- name: CreateRoomPlayer :one
INSERT INTO room_players (room_id, display_name, is_host, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, display_name, is_host, user_id, created_at
`

type CreateRoomPlayerParams struct {
	RoomID      pgtype.UUID `json:"room_id"`
	DisplayName string      `json:"display_name"`
	IsHost      bool        `json:"is_host"`
	UserID      pgtype.UUID `json:"user_id"`
}

type CreateRoomPlayerRow struct {
	ID          pgtype.UUID        `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	DisplayName string             `json:"display_name"`
	IsHost      bool               `json:"is_host"`
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRoomPlayer(ctx context.Context, arg CreateRoomPlayerParams) (CreateRoomPlayerRow, error) {
	row := q.db.QueryRow(ctx, createRoomPlayer,
		arg.RoomID,
		arg.DisplayName,
		arg.IsHost,
		arg.UserID,
	)
	var i CreateRoomPlayerRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.DisplayName,
		&i.IsHost,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, password_hash, settings_json, created_at, updated_at
FROM rooms
WHERE code = $1
`

type GetRoomByCodeRow struct {
	ID           pgtype.UUID        `json:"id"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	SettingsJson []byte             `json:"settings_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (GetRoomByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i GetRoomByCodeRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomCodeById = `-- name: GetRoomCodeById :one
SELECT code FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomCodeById(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getRoomCodeById, id)
	var code string
	err := row.Scan(&code)
	return code, err
}

const getRoomPasswordHashById = `-- name: GetRoomPasswordHashById :one
SELECT password_hash FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomPasswordHashById(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getRoomPasswordHashById, id)
	var password_hash pgtype.Text
	err := row.Scan(&password_hash)
	return password_hash, err
}
